### PR TITLE
Fix Testy.runtests() to run tests in new, top-level module

### LINKED ISSUE #2: Testy.runtests() includes its files into the Testy module
When Testy.runtests() does its `include()` statement, it's including the files into the Testy module.

It's essentially equivalent to running `Core.eval(Testy, parse_whole_file("..."))` (if there was such a `parse_whole_file()`.

This _probably_ shouldn't matter, but it seems to have caused some weirdness with Distributed workers.

Additionally, it might be a problem if a user does `using XX` in their tests, since Julia will complain about replacing any functions exported from XX into the `Testy` module, even if the implementations in XX have changed.

So I'm thinking _probably_ the best approach would be to define a new throw-away module in Main, and do the `include()` into there. Something like this:

```julia
@eval Main begin
    m = @eval Main module $(gensym("TestyModule")) end  # Returns e.g. Main.##TestyModule#365
    m.include("...")  # Perform the include inside module m.
end
```

### PR DESCRIPTION
**Pull request by ghost**
Fixes https://github.com/RelationalAI-oss/Testy.jl/issues/2

### CODE REVIEW

**Comment by ghost** [comment]
@tjgreen  suggested we should just make runtests a macro so that it can execute in the module of the callsite.

We should make this change

**Comment by ghost** [comment]
Thinking a bit more about this, the one thing that I don't love about evaling the `include` within the caller's module is that the behavior of the tests _could_ change depending on what you have already evaluated in that Module.

Julia's built-in `Pkg.test()` spawns a new Julia process, and runs all the tests in `Main` in that process. Could we consider doing something like that, here?

Also, if your tests themselves have any weird statefulness, running them in a separate process would prevent surprising breakages b/w runs.


That logic happens here, for `Pkg.test()`:
https://github.com/JuliaLang/Pkg.jl/blob/40cbbe224d4a491503279dfc5b9aefe15412f007/src/Operations.jl#L1289

**Comment by ghost** [comment]
For now, i think i prefer the implementation currently in this PR to running in the caller's module, since this at least provides _some_ independence (running in a fresh, clean, module), even if it doesn't provide all the independence you'd get from running in a new process.

**Comment by ghost** [comment]
@tjgreen here's a more concrete example of why including the tests into the callers module could fail. This test file currently fails if run more than once, and it would continue to fail if we execute the tests in the caller's module:
```julia
julia> write("/tmp/t.jl", """
           using Testy
           @test !@isdefined f
           f = 5
           @test @isdefined f
       """)
73

julia> using Testy

julia> Testy.runtests("/tmp/t.jl")
Testy.TestyState(String[], 9223372036854775807, r"", r"(?!)", Dict{String,Bool}())

julia> Testy.runtests("/tmp/t.jl")
Test Failed at /tmp/t.jl:2
  Expression: !(#= /tmp/t.jl:2 =# @isdefined(f))
ERROR: LoadError: There was an error during testing
in expression starting at /tmp/t.jl:2
```

However, if we create a new module to run the tests in each time (as I do in this PR), this would succeed:

```julia
julia> newmod = Module(:TM, true)
Main.TM

julia> @eval newmod Base.include(@__MODULE__, "/tmp/t.jl")
Test Passed

julia> newmod = Module(:TM, true)
Main.TM

julia> @eval newmod Base.include(@__MODULE__, "/tmp/t.jl")
Test Passed
```

**Comment by ghost** [comment]
@martin: adding you to review since TJ is out for vacation this week, then i'm out for the next week.

This change seems to me like strictly an improvement, even if it's not the perfect solution. 
This fixes, among other things, running the same test file again after redefining some Delve functions.

**Review by tjgreen42 — APPROVED** [review]
LGTM!

**Pull request merged**
